### ISSUE TITLE
Add support for basic authorization on SVN

### ISSUE THREAD

**Issue by wveeken** [borisdiakur/marked#3]
When trying to display a .md file from our Subversion repository using a URL like this (http://username:password@repo-url), I receive a 401 error.  The SVN log shows that the credentials are removed from the request:
`10.224.64.21 - - [31/Aug/2016:16:46:01 +0200] "GET ////remote_markdown.md HTTP/1.1" 401 734 "-" "Java/1.8.0_65"
`
When using an identical URL in the browser, it works fine.

**Comment by wveeken** [comment]
Thanks, works great!

**Comment by borisdiakur** [comment]
You’re welcome.
