### ISSUE TITLE
Render section of remote markdown

### ISSUE THREAD

**Issue by joesonic** [borisdiakur/marked#5]
Hi,
Is it possible to render just a section/chapter of a remote markdown file instead of the entire file?
e.g. `https://host/mymdfile.md#chaptera`

thanks.

**Comment by borisdiakur** [comment]
Hi @joesonic,
no, at the moment it is not possible to render a section/chapter only with marked. But I am happy to receive PRs anytime ;)

By the way: I’m planning to replace the pegdown parser, which marked is currently using under the hood, with the [flexmark-java](https://github.com/vsch/flexmark-java) parser. If I see some easy way to implement the requested feature, I will reopen this issue.
