### ISSUE TITLE
Support for Syntax-Highlighting

### ISSUE THREAD

**Issue by kiview** [borisdiakur/marked#8]
It seem's there is currently no support for syntax highlighting of embedded code blocks (as seen in Github or Gitlab). I assume this is a more difficult change?

**Comment by borisdiakur** [comment]
Actually that should not be too hard to implement. marked is already using some parser extensions - see [this line](https://github.com/borisdiakur/marked/blob/master/src/main/java/com/borisdiakur/marked/MarkedMacro.java#L85) - here I should be able to just add the [FENCED_CODE_BLOCKS extension](https://github.com/vsch/flexmark-java/wiki/Pegdown-Migration#available-extensions-via-pegdownoptionsadapter) and that should do it. I can try that, as soon as I find some spare time.

**Comment by kiview** [comment]
If you think this is feasible, I might be able to contribute as well, I'll look into this :slightly_smiling_face:.

**Comment by kiview** [comment]
Okay, so basically the parsing seems to already work. The problem seems to be, that flexmark will render the code blocks as a HTML `<code>` block (which is fine in theory).
Confluence however expects a `<table>` based structure around it, to render it like Confluence code macros. So we need to modify the rendered `<code>` tags.

What do you think about restructuring the code a litte bit, to allow for unit testing? It's not much of an effort and it would help in developing this behaviour. I'd do it in this case.

The resulting HTML for Confluence need to look something like this:
```
<div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: java; gutter: false; theme: Confluence" data-theme="Confluence">
System.out.println(&quot;foo&quot;);
int x = 5;


if (5 &gt; 4) {
  int y = asd;
}
</pre>
</div>
```

**Comment by kiview** [comment]
Writing a custom `HtmlRendererExtension` did the trick. Gonna cleanup the code and will create a PR once finished.

**Comment by borisdiakur** [comment]
The only thing I’m not sure about is the `brush` part, which is mandatory. You would somehow need to find out which brush to use (java, js, bash, whatever) by analysing the content of the `<code>` block. If you want to give it a shot and also restructure the project and add unit tests, sure, go for it. Another alternative approach would be to create a flexmark-java extension... You just commented that you just did that. Great! Will you put it in its own repo?

**Comment by kiview** [comment]
Oh, saw your comment a bit to late. If you prefer it, we could extract `ConfluenceCodeBlockExtension` into its own repo. I would be fine to include it in this Confluence specific project, but that's for you to decide :slightly_smiling_face:.

**Comment by borisdiakur** [comment]
No problem, I can live with the extension included here. I’ll have a look in the PR this weekend and probably also publish a new version. Thanks a lot!
